CREATE TABLE IF NOT EXISTS topitem
(
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
	feed_id	TEXT,
    	_id	TEXT UNIQUE
);
CREATE TABLE IF NOT EXISTS frienditem
(
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
	feed_id	TEXT,
    	_id	TEXT UNIQUE
);
CREATE TABLE IF NOT EXISTS recommends
(
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
	feed_id	TEXT,
    	_id	TEXT UNIQUE
);
CREATE TABLE IF NOT EXISTS normalitem
(
	Id INTEGER AUTO_INCREMENT PRIMARY KEY,
	feed_id	TEXT,
    	_id	TEXT UNIQUE
);
ALTER TABLE user ADD COLUMN point INTEGER;
ALTER TABLE comment ADD COLUMN status INTEGER;
ALTER TABLE user ADD COLUMN isFollowingMe INTEGER;
ALTER TABLE feeditem ADD COLUMN seqNumber INTEGER;
ALTER TABLE comment ADD COLUMN floor INTEGER;
ALTER TABLE feeditem ADD COLUMN tag INTEGER;
ALTER TABLE feeditem ADD COLUMN ban_user INTEGER;
ALTER TABLE feeditem ADD COLUMN permission INTEGER;
